### ISSUE TITLE
Teleporters Sometimes Unload/Stop Teleporting or cause Odd Effects

### ISSUE THREAD

**Issue by kitokofox** [ImCoolYeah105/Mechanization#59] opened 2019-01-04 09:27 UTC
Sometimes, teleporters will stop teleporting you to the other side, unless there is someone there on the other side. Also, if someone gets off the teleporter while it's trying to teleport, or when more than one person use the teleporter on both ends ,it causes a phantom force to appear on the teleporter itself. Sometimes, the teleporters themselves exert phantom forces on you.

**Comment by ImCoolYeah105** [comment] 2019-01-04 16:46
Teleporters are a bit broken atm. I'm re-coding them for the next major update, thought that will take awhile.
Closing for being a duplicate of #57 (It's not *exactly* the same issue, but fixing it will also fix this).

**Closed by ImCoolYeah105** 2019-01-04 16:46 UTC

**Comment by Darkspyro911** [comment] 2019-01-04 16:58
so it like in the movies if there are more than one object going thow
teleportation it has bad effects

On 1/4/19, ImCoolYeah105 <notifications@github.com> wrote:
> Teleporters are a bit broken atm. I'm re-coding them for the next major
> update, thought that will take awhile.
> Closing for being a duplicate of #57 (It's not *exactly* the same issue, but
> fixing it will also fix this).
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/59#issuecomment-451498925


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com
