### ISSUE TITLE
Ores not dropping

### ISSUE THREAD

**Issue by Zorknam** [ImCoolYeah105/Mechanization#68] opened 2019-03-10 00:03 UTC
I'm playing on a minecraft Realms with some friends, and the owner asked me to add some interesting Datapacks, so i got Mechanization, everything was working fine, until now, when we break any of the Mechanization ores, we dont get any of them, the owner said he didnt changed any command or nothing, and neither do i, any idea on what may be causing this?

**Comment by ImCoolYeah105** [comment] 2019-03-10 14:16
I don't know what causes this bug, and unless I figure that out I can't fix it. I can say it will be fixed in the next major update.
Closing for duplicate of #50.

**Closed by ImCoolYeah105** 2019-03-10 14:16 UTC

**Comment by Darkspyro911** [comment] 2019-03-10 15:55
it checks if you mined a aphal slab as well how much you picked up a
lot of the time the clear command fails instead when i want to test
for multiple items i do /cear @p diamond 0 than add that number of
items found so if i want to see if the player has 4 diamonds i do
/data get block X Y Z command success count run scoreboard get
itemcount [score] item [fakeplayer] than run a command execute if
score itemcount matches 4.. run clear diamond 4

On 3/10/19, Michael Weatherby <notifications@github.com> wrote:
> I don't know what causes this bug, and unless I figure that out I can't fix
> it. I can say it will be fixed in the next major update.
> Closing for duplicate of #50.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/68#issuecomment-471310159


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com
